[pytest]
testpaths = test
norecursedirs = test/parallel
python_files = test_*.py *_test.py
addopts = --ignore=test/test.txt --ignore=test/test_file.py --ignore=test/test_pos_file.py --ignore=test/test_whoosh_file.py --ignore=test/test_userdict.py
