import argparse
import cProfile
import importlib
import io
import logging
import os
import pstats
import shutil
import signal
import sys
import tempfile
import time
import warnings
from collections.abc import Callable
from multiprocessing import Process, Queue
from types import FrameType
from typing import Any

# Configure logging


# --- Timeout Implementation ---
class TimeoutException(Exception):
    pass


def timeout_handler(signum: int, frame: FrameType | None):
    raise TimeoutException("Test timed out!")


# --- End Timeout Implementation ---

# Suppress specific warnings from jieba or related packages
warnings.filterwarnings(
    "ignore",
    message="pkg_resources is deprecated as an API.*",
    category=UserWarning,
    module="jieba",
)
warnings.filterwarnings(
    "ignore",
    message="Can't find any available. Use default.",
    category=UserWarning,
)


def measure_time(
    func: Callable[..., Any], repetitions: int = 1, *args: Any, **kwargs: Any
) -> tuple[float, Any]:
    """
    Measures the execution time of a function.
    Handles iterators by consuming them to ensure all computation is done.
    """
    total_time = 0.0
    result: Any = None
    for _ in range(repetitions):
        start_time = time.perf_counter()
        result = func(*args, **kwargs)
        # If the result is an iterator, consume it to ensure all computation is done
        if hasattr(result, "__iter__") and not isinstance(
            result, (list, tuple, str, dict, bytes)
        ):
            _ = list(result)
        end_time = time.perf_counter()
        total_time += end_time - start_time
    return total_time / repetitions, result


def clear_all_caches(silent: bool = False):
    """
    Clears all cache files generated by jieba_fast_dat and original jieba.
    """
    if not silent:
        print("Clearing all caches...")

    tmp_dir = tempfile.gettempdir()
    for f in os.listdir(tmp_dir):
        path = os.path.join(tmp_dir, f)

        # Check for unified cache patterns
        is_jieba_cache = f.startswith("jieba.") and (
            f.endswith(".cache") or f.endswith(".cache.dat")
        )
        is_jieba_fast_dat_cache = f.startswith("jieba_fast_dat.") and (
            f.endswith(".cache")
            or f.endswith(".dat")
            or f.endswith(".idf.dat")
            or f.endswith("hmm_models.bin")
        )

        if is_jieba_cache or is_jieba_fast_dat_cache:
            try:
                os.remove(path)
            except OSError:
                pass  # Ignore errors
        # Check for directory caches (like those created by jieba)
        elif f.startswith("jieba.") and os.path.isdir(path):
            shutil.rmtree(path, ignore_errors=True)

    # Note: In single-process mode, we must rely on object deletion (GC)
    # and explicit cache clearing for isolation.

    if not silent:
        print("All caches cleared.")


# ----------------------------------------------------------------------
# Core Testing Function (Runs sequentially)
# ----------------------------------------------------------------------


def _run_library_tests(
    lib_name: str,
    num_repetitions: int,
    custom_dict_path: str,
    user_dict_path: str,
    test_text: str,
    results_queue: Queue,
    timeout_seconds: int = 60,
    # No log_file_path parameter here, each child creates its own temporary log
) -> None:
    """
    Runs the full benchmark suite for a single library.
    Results are put into the results_queue.
    """
    # Each child process creates its own temporary log file
    temp_log_fd, temp_log_path = tempfile.mkstemp(
        prefix=f"benchmark_log_{lib_name}_", suffix=".log"
    )
    temp_log_file = os.fdopen(temp_log_fd, "w", encoding="utf-8", buffering=1)

    # Redirect stdout and stderr to this temporary log file
    original_stdout_fd = os.dup(1)
    original_stderr_fd = os.dup(2)
    os.dup2(temp_log_file.fileno(), 1)  # Redirect stdout
    os.dup2(temp_log_file.fileno(), 2)  # Redirect stderr

    # Reconfigure logging for this child process
    for handler in logging.root.handlers[:]:
        logging.root.removeHandler(handler)
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(levelname)s - %(message)s",
        stream=sys.stdout,
    )

    profiler = cProfile.Profile()
    profiler.enable()

    # --- Actual test execution will start here ---
    print(f"\n--- Starting tests for: {lib_name} ---")

    lib_results: dict[str, Any] = {}
    child_error_encountered = False  # Flag for errors in this child process.

    # 1. Dynamically import the required modules
    try:
        # We assume the library is not imported yet, or we're using a fresh environment.
        # If the library was previously imported, Python might reuse the module object.
        # However, for external fast libraries, dynamic import is usually sufficient
        # as they handle initialization on Tokenizer creation/initialize() call.
        lib_module = importlib.import_module(lib_name)
        Tokenizer = lib_module.Tokenizer
    except ImportError as e:
        print(f"Error loading {lib_name} or {lib_name}.posseg: {e}", file=sys.stderr)
        results_queue.put((lib_name, {"error": str(e)}))
        return

    lib_results: dict[str, Any] = {}

    # --- Test 1: Cold Start Dictionary Initialization (No Cache, Force Rebuild) ---
    def cold_init():
        # Crucial step: Clear caches *before* measuring cold start
        clear_all_caches(silent=True)
        tokenizer = Tokenizer(dictionary=custom_dict_path)
        # Use initialize(force_rebuild=True) for lib_fast_dat to ensure cache regen
        if lib_name == "jieba_fast_dat":
            tokenizer.initialize(force_rebuild=True)
        else:
            tokenizer.initialize()
        # Force dictionary usage to trigger full load if lazy
        _ = list(tokenizer.lcut(test_text))
        return tokenizer

    try:
        print("Measuring 1. Cold Init...")
        signal.signal(signal.SIGALRM, timeout_handler)
        signal.alarm(timeout_seconds)
        first_init_time, _ = measure_time(cold_init, 1)
        signal.alarm(0)  # Disable the alarm
        lib_results["first_init_time"] = first_init_time
    except TimeoutException:
        signal.alarm(0)  # Ensure alarm is disabled
        lib_results["first_init_time"] = float("inf")
        logging.error(
            f"❌ {lib_name} Cold Init timed out after {timeout_seconds} seconds."
        )
    except Exception as e:
        signal.alarm(0)  # Ensure alarm is disabled on other exceptions
        lib_results["first_init_time"] = float("inf")
        logging.error(f"⚠️ {lib_name} Cold Init Error: {e}", exc_info=True)

    # --- Test 2: Warm Start Dictionary Initialization (With Cache/Memory) ---
    # The previous cold_init call should have generated the cache/loaded into memory
    def warm_init():
        # Create a new Tokenizer instance to test warm startup from cache/memory
        tokenizer = Tokenizer(dictionary=custom_dict_path)
        tokenizer.initialize()
        # Force dictionary usage to trigger full load if lazy
        _ = list(tokenizer.lcut(test_text))
        return tokenizer

    try:
        print("Measuring 2. Warm Init...")
        signal.signal(signal.SIGALRM, timeout_handler)
        signal.alarm(timeout_seconds)
        # Use the result (final_tokenizer) for subsequent tests
        second_init_time, final_tokenizer = measure_time(warm_init, num_repetitions)
        signal.alarm(0)  # Disable the alarm
        lib_results["second_init_time"] = second_init_time
    except TimeoutException:
        signal.alarm(0)  # Ensure alarm is disabled
        lib_results["second_init_time"] = float("inf")
        logging.error(
            f"❌ {lib_name} Warm Init timed out after {timeout_seconds} seconds."
        )
        results_queue.put((lib_name, lib_results))  # Put incomplete results
        return
    except Exception as e:
        signal.alarm(0)  # Ensure alarm is disabled on other exceptions
        lib_results["second_init_time"] = float("inf")
        logging.error(f"⚠️ {lib_name} Warm Init Error: {e}", exc_info=True)
        results_queue.put((lib_name, lib_results))  # Put incomplete results
        return

    # --- Test X: HMM Model Load ---
    # Measure the time it takes to import the posseg module (which loads HMM models)
    # This also assigns lib_posseg_module for later use
    lib_posseg_module = None  # Initialize to None
    try:
        print("Measuring X. HMM Model Load...")
        signal.signal(signal.SIGALRM, timeout_handler)
        signal.alarm(timeout_seconds)
        # First, import the module to make load_model available
        _lib_posseg_module = importlib.import_module(f"{lib_name}.posseg")
        # Then, measure the actual load_model function
        hmm_load_time, _ = measure_time(_lib_posseg_module.load_model, 1)
        lib_posseg_module = _lib_posseg_module  # Assign the result
        signal.alarm(0)  # Disable the alarm
        lib_results["HMM_model_load_time"] = hmm_load_time

    except TimeoutException:
        signal.alarm(0)
        lib_results["HMM_model_load_time"] = float("inf")
        logging.error(
            f"❌ {lib_name} HMM Model Load timed out after {timeout_seconds} seconds."
        )
    except Exception as e:
        signal.alarm(0)
        lib_results["HMM_model_load_time"] = float("inf")
        logging.error(f"⚠️ {lib_name} HMM Model Load Error: {e}", exc_info=True)

    # --- Test 3: User Dictionary Loading Performance ---
    try:
        print("Measuring 3. User Dict Load (No Cache)...")
        # Clear user dict cache before the "No Cache" test
        if lib_name == "jieba_fast_dat":
            user_cache_file = lib_module._get_user_dict_cache_paths(user_dict_path)
            dat_cache_file = user_cache_file.with_suffix(".dat")
            user_cache_file.unlink(missing_ok=True)
            dat_cache_file.unlink(missing_ok=True)

        signal.signal(signal.SIGALRM, timeout_handler)
        signal.alarm(timeout_seconds)
        user_dict_load_time_no_cache, _ = measure_time(
            final_tokenizer.load_userdict,
            1,
            user_dict_path,  # Run only once for cold start
        )
        signal.alarm(0)  # Disable the alarm
        lib_results["user_dict_load_time_no_cache"] = user_dict_load_time_no_cache

        print("Measuring 3.1. User Dict Load (With Cache)...")
        signal.signal(signal.SIGALRM, timeout_handler)
        signal.alarm(timeout_seconds)
        user_dict_load_time_with_cache, _ = measure_time(
            final_tokenizer.load_userdict, num_repetitions, user_dict_path
        )
        signal.alarm(0)  # Disable the alarm
        lib_results["user_dict_load_time_with_cache"] = user_dict_load_time_with_cache

    except TimeoutException:
        signal.alarm(0)  # Ensure alarm is disabled
        lib_results["user_dict_load_time_no_cache"] = float("inf")
        lib_results["user_dict_load_time_with_cache"] = float("inf")
        logging.error(
            f"❌ {lib_name} User Dict Load timed out after {timeout_seconds} seconds."
        )
    except Exception as e:
        signal.alarm(0)  # Ensure alarm is disabled on other exceptions
        lib_results["user_dict_load_time_no_cache"] = float("inf")
        lib_results["user_dict_load_time_with_cache"] = float("inf")
        logging.error(f"⚠️ {lib_name} User Dict Load Error: {e}", exc_info=True)

    # Set up POSSEG for subsequent tests
    try:
        if lib_posseg_module is None:
            # If HMM module load failed, try to load it now (it might still fail)
            lib_posseg_module = importlib.import_module(f"{lib_name}.posseg")
        posseg_tokenizer = lib_posseg_module.dt
        # Use the tokenizer that now includes both main and user dictionaries
        posseg_tokenizer.tokenizer = final_tokenizer
    except Exception as e:
        print(f"⚠️ {lib_name} POSSEG setup Error: {e}", file=sys.stderr)

    # --- Test 4: Segmentation and POS Tagging Performance (HMM=False) ---
    try:
        print("Measuring 4. Cut (HMM=False)...")
        signal.signal(signal.SIGALRM, timeout_handler)
        signal.alarm(timeout_seconds)
        cut_time, _ = measure_time(
            final_tokenizer.cut, num_repetitions, test_text, HMM=False
        )
        signal.alarm(0)  # Disable the alarm
        lib_results["cut_time_HMM_False"] = cut_time
    except TimeoutException:
        signal.alarm(0)  # Ensure alarm is disabled
        lib_results["cut_time_HMM_False"] = float("inf")
        logging.error(
            f"❌ {lib_name} Cut (HMM=False) timed out after {timeout_seconds} seconds."
        )
    except Exception as e:
        signal.alarm(0)  # Ensure alarm is disabled on other exceptions
        lib_results["cut_time_HMM_False"] = float("inf")
        logging.error(f"⚠️ {lib_name} HMM=False Cut Error: {e}", exc_info=True)

    try:
        print("Measuring 5. POS (HMM=False)...")
        signal.signal(signal.SIGALRM, timeout_handler)
        signal.alarm(timeout_seconds)
        pos_time, _ = measure_time(
            posseg_tokenizer.cut, num_repetitions, test_text, HMM=False
        )
        signal.alarm(0)  # Disable the alarm
        lib_results["pos_time_HMM_False"] = pos_time
    except TimeoutException:
        signal.alarm(0)  # Ensure alarm is disabled
        lib_results["pos_time_HMM_False"] = float("inf")
        logging.error(
            f"❌ {lib_name} POS (HMM=False) timed out after {timeout_seconds} seconds."
        )
    except Exception as e:
        signal.alarm(0)  # Ensure alarm is disabled on other exceptions
        lib_results["pos_time_HMM_False"] = float("inf")
        logging.error(f"⚠️ {lib_name} HMM=False POS Error: {e}", exc_info=True)

    # --- Test 5: Segmentation and POS Tagging Performance (HMM=True) ---
    try:
        print("Measuring 6. Cut (HMM=True)...")
        signal.signal(signal.SIGALRM, timeout_handler)
        signal.alarm(timeout_seconds)
        cut_hmm_true_time, _ = measure_time(
            final_tokenizer.cut, num_repetitions, test_text, HMM=True
        )
        signal.alarm(0)  # Disable the alarm
        lib_results["cut_time_HMM_True"] = cut_hmm_true_time
    except TimeoutException:
        signal.alarm(0)  # Ensure alarm is disabled
        lib_results["cut_time_HMM_True"] = float("inf")
        logging.error(
            f"❌ {lib_name} Cut (HMM=True) timed out after {timeout_seconds} seconds."
        )
    except Exception as e:
        signal.alarm(0)  # Ensure alarm is disabled on other exceptions
        lib_results["cut_time_HMM_True"] = float("inf")
        logging.error(f"⚠️ {lib_name} HMM=True Cut Error: {e}", exc_info=True)

    try:
        print("Measuring 7. POS (HMM=True)...")
        signal.signal(signal.SIGALRM, timeout_handler)
        signal.alarm(timeout_seconds)
        pos_hmm_true_time, _ = measure_time(
            posseg_tokenizer.cut, num_repetitions, test_text, HMM=True
        )
        signal.alarm(0)  # Disable the alarm
        lib_results["pos_time_HMM_True"] = pos_hmm_true_time
    except TimeoutException:
        signal.alarm(0)  # Ensure alarm is disabled
        lib_results["pos_time_HMM_True"] = float("inf")
        logging.error(
            f"❌ {lib_name} POS (HMM=True) timed out after {timeout_seconds} seconds."
        )
    except Exception as e:
        signal.alarm(0)  # Ensure alarm is disabled on other exceptions
        lib_results["pos_time_HMM_True"] = float("inf")
        logging.error(f"⚠️ {lib_name} HMM=True POS Error: {e}", exc_info=True)

    profiler.disable()
    print(f"\n--- cProfile Stats for {lib_name} ---\n")
    s = io.StringIO()
    sortby = pstats.SortKey.CUMULATIVE
    ps = pstats.Stats(profiler, stream=s).sort_stats(sortby)
    ps.print_stats(500)
    print(s.getvalue())
    # Crucial: Explicitly delete tokenizer reference to help GC free memory
    del final_tokenizer
    if "posseg_tokenizer" in locals():
        del posseg_tokenizer

    # Ensure all buffered output is written to the temporary log file
    sys.stdout.flush()
    sys.stderr.flush()

    # Restore original stdout/stderr file descriptors
    os.dup2(original_stdout_fd, 1)
    os.dup2(original_stderr_fd, 2)
    os.close(original_stdout_fd)
    os.close(original_stderr_fd)

    # Close the temporary log file handle
    temp_log_file.close()

    # Pass the temporary log file path back along with results
    results_queue.put((lib_name, lib_results, temp_log_path))


def run_performance_test():
    print(
        "Starting multiprocessing performance comparison (jieba vs. jieba_fast_dat)..."
    )
    print("✅ Each library's benchmark is now run in a separate process.")
    print("For better isolation.")

    # Define file paths
    current_dir = os.path.dirname(os.path.abspath(__file__))
    base_dir = os.path.join(current_dir, "..")
    custom_dict_path = os.path.join(base_dir, "extra_dict", "dict.txt.big")
    user_dict_path = os.path.join(base_dir, "extra_dict", "dict.txt.big.tw_nerd.txt")
    test_text_path = os.path.join(base_dir, "extra_dict", "profile_test")

    # Check if files exist
    required_files: list[tuple[str, str]] = [
        ("Custom dictionary", custom_dict_path),
        ("User dictionary", user_dict_path),
        ("Test text", test_text_path),
    ]
    for desc, path in required_files:
        if not os.path.exists(path):
            print(f"Error: {desc} file not found at {path}")
            sys.exit(1)

    # Read test text
    with open(test_text_path, encoding="utf-8") as f:
        long_text = f.read()

    NUM_REPETITIONS = 10  # Define repetition count for each test
    DEFAULT_TIMEOUT_SECONDS = (
        600  # Default timeout for each test in seconds, can be adjusted (10 minutes)
    )

    results: dict[str, dict[str, float]] = {}
    libraries = ["jieba", "jieba_fast_dat"]

    results_queue = Queue()
    processes = []

    for lib_name in libraries:
        p = Process(
            target=_run_library_tests,
            args=(
                lib_name,
                NUM_REPETITIONS,
                custom_dict_path,
                user_dict_path,
                long_text,
                results_queue,
                DEFAULT_TIMEOUT_SECONDS,  # Pass timeout parameter
            ),
        )
        processes.append(p)
        p.start()

    for p in processes:
        p.join()

    # Collect results and log file paths from the queue
    child_log_files: list[str] = []
    for _ in libraries:
        lib_name, lib_results, temp_log_path = results_queue.get()
        results[lib_name] = lib_results
        child_log_files.append(temp_log_path)

    # After collecting all results, merge child process logs into the main log file
    # This ensures ordered logging from each child process.
    for temp_log_path in child_log_files:
        try:
            with open(temp_log_path, encoding="utf-8") as temp_f:
                # Use sys.stdout.write to write directly to the redirected main log file
                sys.stdout.write(
                    f"\n--- Log from {os.path.basename(temp_log_path)} "
                    f"for {os.path.basename(temp_log_path).split('_')[2]} ---\n"
                )
                sys.stdout.write(temp_f.read())
                sys.stdout.write(
                    f"\n--- End Log from {os.path.basename(temp_log_path)} ---\n"
                )
                sys.stdout.flush()  # Ensure it's written immediately
        except Exception as e:
            logging.error(
                f"Error merging temporary log {temp_log_path}: {e}", exc_info=True
            )
        finally:
            # Clean up temporary log file
            if os.path.exists(temp_log_path):
                os.remove(temp_log_path)

    # --- Print Summary ---
    print("\n" + "=" * 92)
    print("--- Final Summary: Performance Comparison (Time in seconds) ---")
    print("=" * 92)

    if not all(lib in results and "error" not in results[lib] for lib in libraries):
        print("⚠️ One or more libraries failed to complete tests. See log for details.")

    metrics: list[tuple[str, str]] = [
        ("Initial Main Dict Load (No Cache)", "first_init_time"),
        ("Initial Main Dict Load (With Cache)", "second_init_time"),
        ("HMM Model Load", "HMM_model_load_time"),
        ("User Dict Load (No Cache)", "user_dict_load_time_no_cache"),
        ("User Dict Load (With Cache)", "user_dict_load_time_with_cache"),
        ("Word Segmentation (HMM=False)", "cut_time_HMM_False"),
        ("POS Tagging (HMM=False)", "pos_time_HMM_False"),
        ("Word Segmentation (HMM=True)", "cut_time_HMM_True"),
        ("POS Tagging (HMM=True)", "pos_time_HMM_True"),
    ]

    print(f"{'Metric':<40} {'Jieba':>15} {'Jieba_fast_dat':>20} {'Speedup':>15}")
    print("-" * 92)

    jieba_results = results.get("jieba", {})
    jieba_fast_dat_results = results.get("jieba_fast_dat", {})

    for desc, key in metrics:
        jieba_time = jieba_results.get(key, float("inf"))
        fast_dat_time = jieba_fast_dat_results.get(key, float("inf"))

        if jieba_time == float("inf") or fast_dat_time == float("inf"):
            speedup_str = "N/A"
            jieba_time_str = "N/A"
            fast_dat_time_str = "N/A"
        else:
            jieba_time_str = f"{jieba_time:.7f}s"
            fast_dat_time_str = f"{fast_dat_time:.7f}s"

            if fast_dat_time < jieba_time:
                speedup = jieba_time / fast_dat_time
                speedup_str = f"**{speedup:.2f}x** faster"
            else:
                slowdown = fast_dat_time / jieba_time
                speedup_str = f"{slowdown:.2f}x slower"

        print(
            f"{desc:<40} {jieba_time_str:>15} {fast_dat_time_str:>20} {speedup_str:>15}"
        )


if __name__ == "__main__":
    # Ensure multiprocessing starts cleanly on various OS
    # This is important for frozen executables (e.g., PyInstaller)
    # and might be beneficial for general robustness.
    import multiprocessing

    multiprocessing.set_start_method("spawn", force=True)

    parser = argparse.ArgumentParser(
        description=(
            "Run sequential performance comparison between jieba and jieba_fast_dat."
        )
    )
    parser.add_argument(
        "--output",
        type=str,
        default="tmp/performance_comparison.log",
        help="Path to the output log file.",
    )
    args = parser.parse_args()

    log_file_path = args.output

    # Back up original stdout/stderr file descriptors before potential redirection
    original_stdout_fd = os.dup(1)
    original_stderr_fd = os.dup(2)

    try:
        # Ensure the directory exists if not already present
        os.makedirs(os.path.dirname(log_file_path), exist_ok=True)
        with open(log_file_path, "w", encoding="utf-8") as f:
            # Duplicate file descriptor to stdout (fd 1) and stderr (fd 2).
            # All prints and C module outputs go to log file.
            os.dup2(f.fileno(), 1)  # Redirect stdout to log file
            os.dup2(f.fileno(), 2)  # Redirect stderr to log file

            # Reconfigure logging to use redirected sys.stdout (our log file).
            # This is important for logging messages from Python code.
            for handler in logging.root.handlers[:]:  # Remove existing handlers
                logging.root.removeHandler(handler)
            logging.basicConfig(
                level=logging.INFO,
                format="%(asctime)s - %(levelname)s - %(message)s",
                stream=sys.stdout,
            )

            run_performance_test()

            # Explicitly flush stdout/stderr to ensure all output is written.
            sys.stdout.flush()
            sys.stderr.flush()

            logging.info(f"Multiprocessing results saved to {log_file_path}")
            for handler in logging.root.handlers:
                if hasattr(handler, "flush"):
                    handler.flush()
    except Exception as e:
        # Logging should now go to the redirected stderr (log file)
        logging.error(f"An error occurred during the benchmark: {e}", exc_info=True)
    finally:
        # Restore original stdout/stderr for proper console output after script exit.
        os.dup2(original_stdout_fd, 1)
        os.dup2(original_stderr_fd, 2)
        os.close(original_stdout_fd)
        os.close(original_stderr_fd)
